### ISSUE TITLE
F1 score and dataset

### ISSUE THREAD

**Issue by kkkgh111** [ark1234/CP-Net#1]
Hello!I would like to inquire about whether the F1 score in the paper was not imported into the ChamferDistancePython library in GitHub?Also, regarding the ShapeNet dataset and Completion3D dataset mentioned in the paper, could you provide a download link for the dataset? The Completion3D link has expired.Thank you very much!

**Comment by ark1234** [comment]
Thanks for your interest in our work!
Here is the link for F1 and CD: https://github.com/ThibaultGROUEIX/ChamferDistancePytorch
Here is the link for ShapeNet: https://drive.google.com/drive/folders/1P_W1tz5Q4ZLapUifuOE4rFAZp6L1XTJz
Here is the link for Completion3D: http://download.cs.stanford.edu/downloads/completion3d/dataset2019.zip

**Comment by kkkgh111** [comment]
Thank you very much. Do you use wechat? Is it convenient to leave a contact information?



---Original---
From: "Ark ***@***.***&gt;
Date: Sat, Jul 15, 2023 23:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ark1234/CP-Net] F1 score and dataset (Issue #1)




 
Thanks for your interest in our work!
 Here is the link for F1 and CD: https://github.com/ThibaultGROUEIX/ChamferDistancePytorch
 Here is the link for ShapeNet: https://drive.google.com/drive/folders/1P_W1tz5Q4ZLapUifuOE4rFAZp6L1XTJz
 Here is the link for Completion3D: http://download.cs.stanford.edu/downloads/completion3d/dataset2019.zip
